import './globals.css'
import '../styles/main.module.scss';
import '../styles/bootstrap/css/bootstrap-grid.css';
import {Outfit} from "next/font/google"
import styles from '../styles/main.module.scss';


const outfit = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles['styleguide']}>
      <div className={outfit.className}>
        {children}
      </div>
      </body>
    </html>
  )
}
